server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin996
    url: jdbc:mysql://172.23.148.54:3306/shop-app?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
mybatis:
  mapper-locations: classpath:mapper/*.xml
