# 这里的配置属性只是基础配置，如需更多功能配置，请自行扩展
dubbo:
  application:
    name: dubbo-provider
    register-mode: instance
#    register-mode: all
    service-discovery:
      migration: APPLICATION_FIRST
  registry:
    address: zookeeper://172.23.148.54:2181
  protocol:
    name: dubbo
    port: 20880
    host: 192.168.1.6
#  provider:
#    tag: p1
tag: provider1
