server:
  port: 8083
mail:
  hostName: zzzx@qq.com
  port: 2122
  from: xxxa
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
