# 数据库访问配置
# 主数据源，默认的
spring:
  datasource:
    url: jdbc:mysql://zhuyc.top:13306/druid?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: '123456'
