# 数据库访问配置
# 主数据源，默认的
spring:
  datasource:
    url: jdbc:mysql://${IP}:${PORT}/druid?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: ${USER_NAME}
    password: ${PASSWORD}
