# 这里的配置属性只是基础配置，如需更多功能配置，请自行扩展
dubbo:
  application:
    qos-enable: false
    name: dubbo-provider
    register-mode: instance
    service-discovery:
      migration: APPLICATION_FIRST
  registry:
    address: zookeeper://172.23.148.54:2181
#  provider:
#    prefer-serialization: protobuf
#    serialization: protobuf
  protocols:
    tri1:
      name: tri
      port: 50052
      host: 192.168.1.6
#      serialization: protobuf
#    dubbo1:
#      name: dubbo
#      port: 20882
#      host: 192.168.1.6

#  provider:
#    tag: p2
tag: provider2
server:
  port: 8082

