// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source:  Greeter.proto

package org.apache.dubbo.samples.api;

public interface GreeterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.dubbo.samples.api.GreeterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
