
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_quartz?characterEncoding=utf8&characterSetResults=utf8&useSSL=false&eserverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always #是否需要执行建表语句
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 3


